# Generated by Django 3.2.5 on 2021-07-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='point',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_pk',
        ),
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('mju', 'MJU'), ('not-specified', 'Not Specified'), ('uplex', 'UPLEX')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zonecode',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
