# Generated by Django 3.2.5 on 2021-07-08 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('dept', models.CharField(choices=[('uplex', 'UPLEX'), ('mju', 'MJU'), ('not-specified', 'Not Specified')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('nickname', models.CharField(max_length=20, null=True, unique=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('zonecode', models.CharField(default=0, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
