# Generated by Django 3.2.5 on 2021-07-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_alter_profile_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
